import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the standalone "Uputstvo" docs instance.
// Chapters are auto-generated from the uputstvo/ folder order (sidebar_position).
const sidebars: SidebarsConfig = {
  uputstvoSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
